title: "Cristina Aranzana Moreno"
description: "PhD Candidate in Economics at University of Barcelona"
email: "c.aranzana@ub.edu"

baseurl: ""
url: "https://cristinaaranzana.github.io"

nav:
  - title: "Home"
    url: "/"
  - title: "Research"
    url: "/research"
  - title: "CV"
    url: "/cv"
